package core.data;
import java.util.*;
import java.io.*;

import core.Item;
import core.ItemSet;
/**
 * This class was generated by a SmartGuide.
 *  
 */
public class AsciiDatabase extends Database {
	private String fileName;
	class AsciiFileEnumeration extends DataEnumeration {
		private BufferedReader in;
		/**
		 * nextItemSet method comment.
		 */
		protected AsciiFileEnumeration() {
			current = nextItemSet();
		}

		protected ItemSet nextItemSet() {
			if (in == null)
				try {
					in = new BufferedReader(new FileReader(fileName));
				} catch (FileNotFoundException e) {
					System.out.println("Could not open " + fileName);
				}
			try {
				String s = in.readLine();
				if (s != null) {
					StringTokenizer st = new StringTokenizer(s);
					ItemSet itemset = new ItemSet();
					Item item;
					while (st.hasMoreTokens()) {
						item = new Item(st.nextToken());
						itemset.addElement(item);
					}
					return itemset;
				} else {
					return null;
				}
			} catch (IOException e) {
				System.out.println("st.nextToken() unsuccessful");
				return null;
			}
		}/* (non-Javadoc)
		 * @see java.util.Enumeration#hasMoreElements()
		 */
	}
	/**
	 * Defines an object of type AsciiDatabase which maps a file to a database
	 * 
	 * @param FileName
	 *            java.lang.String
	 */
	public AsciiDatabase(String FileName) {
		fileName = FileName;
		bulk_load();
	}
	/**
	 * This method was created by a SmartGuide. Inits a text file for reading of
	 * 
	 * @param FileName
	 *            java.lang.String
	 */
	public AsciiDatabase(String FileName, boolean toload) {
		fileName = FileName;
		load = toload;
		if (load)
			bulk_load();
	}
	/**
	 * Insert the method's description here. Creation date: (16/02/2003 1.05.48)
	 * 
	 * @return java.util.Enumeration
	 */
	public Enumeration getEnumeration() {
		return new AsciiFileEnumeration();
	}
	public static void main(String[] args){
		Database data = new AsciiDatabase("C:/WUtemp/cazz.txt");
		for (Enumeration e = data.elements(); e.hasMoreElements();)
			System.out.println(e.nextElement());
	}
}