package core;

import java.util.*;
/**
 * This class was generated by a SmartGuide.
 * 
 */
class SortVector extends Vector {
/**
	 * Comment for <code>serialVersionUID</code>
	 */
	private static final long serialVersionUID = 1L;
/**
 * This method was created by a SmartGuide.
 * @param left int
 * @param right int
 */
private void quickSort (int left, int right) {
	if (right > left){
		Object o1 = elementAt(right);
		int i = left -1;
		int j = right;
		while (true){
			while (((Item)elementAt(++i)).lessThan(o1))
				;
			while (j>0)
				if (((Item)elementAt(--j)).lessThanOrEqual(o1))
				break;
			if (i>=j) break;
			swap(i,j);
		}
		swap(i, right);
		quickSort(left, i-1);
		quickSort(i+1, right);
	}			 
}
/**
 * This method was created by a SmartGuide.
 */
public void sort ( ) {
	quickSort(0, size()-1);
}
/**
 * This method was created by a SmartGuide.
 * @param loc1 int
 * @param loc2 int
 */
private void swap (int loc1, int loc2) {
	Object tmp = elementAt(loc1);
	setElementAt(elementAt(loc2), loc1);
	setElementAt(tmp, loc2);
}
}
